<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Linkpearl.Audio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
    <PackageReference Include="NLayer" Version="1.16.0" />
    <PackageReference Include="NLayer.NAudioSupport" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Linkpearl.Abstractions\Linkpearl.Abstractions.csproj" />
  </ItemGroup>

</Project>
