namespace Linkpearl.Preferences;

public static partial class PhoneLanguages
{
    private static readonly Dictionary<string, Dictionary<string, string>> Ui =
        new(StringComparer.Ordinal)
        {
            ["ui.open"] = Lang(("en", "Open"), ("ja", "開く"), ("de", "Öffnen"), ("fr", "Ouvrir"),
                ("es", "Abrir"), ("pt", "Abrir"), ("it", "Apri"), ("zh-CN", "打开"), ("zh-TW", "開啟"),
                ("ko", "열기"), ("ru", "Открыть")),
            ["ui.close"] = Lang(("en", "Close"), ("ja", "閉じる"), ("de", "Schließen"), ("fr", "Fermer"),
                ("es", "Cerrar"), ("pt", "Fechar"), ("it", "Chiudi"), ("zh-CN", "关闭"), ("zh-TW", "關閉"),
                ("ko", "닫기"), ("ru", "Закрыть")),
            ["ui.search"] = Lang(("en", "Search"), ("ja", "検索"), ("de", "Suchen"), ("fr", "Rechercher"),
                ("es", "Buscar"), ("pt", "Buscar"), ("it", "Cerca"), ("zh-CN", "搜索"), ("zh-TW", "搜尋"),
                ("ko", "검색"), ("ru", "Поиск")),
            ["ui.done"] = Lang(("en", "Done"), ("ja", "完了"), ("de", "Fertig"), ("fr", "OK"),
                ("es", "Listo"), ("pt", "Concluído"), ("it", "Fine"), ("zh-CN", "完成"), ("zh-TW", "完成"),
                ("ko", "완료"), ("ru", "Готово")),
            ["ui.back"] = Lang(("en", "Back"), ("ja", "戻る"), ("de", "Zurück"), ("fr", "Retour"),
                ("es", "Atrás"), ("pt", "Voltar"), ("it", "Indietro"), ("zh-CN", "返回"), ("zh-TW", "返回"),
                ("ko", "뒤로"), ("ru", "Назад")),
            ["ui.manage"] = Lang(("en", "Manage"), ("ja", "管理"), ("de", "Verwalten"), ("fr", "Gérer"),
                ("es", "Gestionar"), ("pt", "Gerenciar"), ("it", "Gestisci"), ("zh-CN", "管理"), ("zh-TW", "管理"),
                ("ko", "관리"), ("ru", "Управление")),
            ["set.general.blurb"] = Lang(("en", "Lock, combat, and how the phone behaves"),
                ("ja", "ロック、戦闘、端末の動作"), ("de", "Sperre, Kampf und Verhalten"),
                ("fr", "Verrouillage, combat et comportement"), ("es", "Bloqueo, combate y comportamiento"),
                ("pt", "Bloqueio, combate e comportamento"), ("it", "Blocco, combattimento e comportamento"),
                ("zh-CN", "锁定、战斗与手机行为"), ("zh-TW", "鎖定、戰鬥與手機行為"),
                ("ko", "잠금, 전투, 휴대폰 동작"), ("ru", "Блок, бой и поведение")),
            ["set.profile.blurb"] = Lang(("en", "Portrait, name, and which character holds Calendar, Pearls, and Phone notes"),
                ("ja", "肖像、名前、カレンダー・パール・電話メモの担当キャラクター"),
                ("de", "Porträt, Name und welcher Charakter Kalender, Pearls und Telefonnotizen hält"),
                ("fr", "Portrait, nom, et quel personnage tient le calendrier, les Pearls et les notes téléphone"),
                ("es", "Retrato, nombre y qué personaje guarda calendario, Pearls y notas del teléfono"),
                ("pt", "Retrato, nome e qual personagem guarda calendário, Pearls e notas do telefone"),
                ("it", "Ritratto, nome e quale personaggio tiene calendario, Pearls e note telefono"),
                ("zh-CN", "头像、名称，以及哪个角色保存日历、Pearls 与电话备忘"),
                ("zh-TW", "頭像、名稱，以及哪個角色保存日曆、Pearls 與電話備忘"),
                ("ko", "초상, 이름, 캘린더·Pearls·전화 메모를 가진 캐릭터"),
                ("ru", "Портрет, имя и какой персонаж хранит календарь, Pearls и заметки телефона")),
            ["set.appearance.blurb"] = Lang(("en", "Themes, display, wallpaper, and home"),
                ("ja", "テーマ、表示、壁紙、ホーム"), ("de", "Themen, Anzeige, Hintergrund und Start"),
                ("fr", "Thèmes, affichage, fond et accueil"), ("es", "Temas, pantalla, fondo e inicio"),
                ("pt", "Temas, tela, papel de parede e início"), ("it", "Temi, display, sfondo e home"),
                ("zh-CN", "主题、显示、壁纸与主屏幕"), ("zh-TW", "主題、顯示、桌布與主畫面"),
                ("ko", "테마, 화면, 배경, 홈"), ("ru", "Темы, экран, обои и дом")),
            ["set.sounds.blurb"] = Lang(("en", "Speaker, microphone, and volume"),
                ("ja", "スピーカー、マイク、音量"), ("de", "Lautsprecher, Mikrofon und Lautstärke"),
                ("fr", "Haut-parleur, micro et volume"), ("es", "Altavoz, micrófono y volumen"),
                ("pt", "Alto-falante, microfone e volume"), ("it", "Altoparlante, microfono e volume"),
                ("zh-CN", "扬声器、麦克风和音量"), ("zh-TW", "喇叭、麥克風與音量"),
                ("ko", "스피커, 마이크, 음량"), ("ru", "Динамик, микрофон и громкость")),
            ["set.notifications.blurb"] = Lang(("en", "Do not disturb and badges"),
                ("ja", "通知オフとバッジ"), ("de", "Nicht stören und Markierungen"),
                ("fr", "Ne pas déranger et badges"), ("es", "No molestar y distintivos"),
                ("pt", "Não perturbe e selos"), ("it", "Non disturbare e badge"),
                ("zh-CN", "勿扰与角标"), ("zh-TW", "勿擾與標記"),
                ("ko", "방해 금지와 배지"), ("ru", "Не беспокоить и значки")),
            ["set.feed.blurb"] = Lang(("en", "Which live channels appear"),
                ("ja", "表示するライブチャンネル"), ("de", "Welche Live-Kanäle erscheinen"),
                ("fr", "Canaux live affichés"), ("es", "Qué canales en vivo aparecen"),
                ("pt", "Quais canais ao vivo aparecem"), ("it", "Quali canali live appaiono"),
                ("zh-CN", "显示哪些实时频道"), ("zh-TW", "顯示哪些即時頻道"),
                ("ko", "표시할 실시간 채널"), ("ru", "Какие каналы показывать")),
            ["set.calls.blurb"] = Lang(("en", "Calls, wake, and portraits"),
                ("ja", "通話、起動、ポートレート"), ("de", "Anrufe, Aufwecken und Porträts"),
                ("fr", "Appels, réveil et portraits"), ("es", "Llamadas, activación y retratos"),
                ("pt", "Chamadas, despertar e retratos"), ("it", "Chiamate, riattivazione e ritratti"),
                ("zh-CN", "来电、唤醒与肖像"), ("zh-TW", "通話、喚醒與肖像"),
                ("ko", "통화, 깨우기, 초상"), ("ru", "Звонки, пробуждение и портреты")),
            ["set.tos.blurb"] = Lang(("en", "How this phone may be used"),
                ("ja", "この端末の利用について"), ("de", "Wie dieses Telefon genutzt werden darf"),
                ("fr", "Conditions d’usage de ce téléphone"), ("es", "Cómo se puede usar este teléfono"),
                ("pt", "Como este telefone pode ser usado"), ("it", "Come si può usare questo telefono"),
                ("zh-CN", "本手机的使用方式"), ("zh-TW", "本手機的使用方式"),
                ("ko", "이 휴대폰 이용 안내"), ("ru", "Как можно пользоваться телефоном")),
            ["set.themes"] = Lang(("en", "Themes"), ("ja", "テーマ"), ("de", "Themen"), ("fr", "Thèmes"),
                ("es", "Temas"), ("pt", "Temas"), ("it", "Temi"), ("zh-CN", "主题"), ("zh-TW", "主題"),
                ("ko", "테마"), ("ru", "Темы")),
            ["set.themes.blurb"] = Lang(("en", "Default theme, accent color, and text size"),
                ("ja", "テーマ、アクセント、文字サイズ"), ("de", "Standardthema, Akzentfarbe und Textgröße"),
                ("fr", "Thème, accent et taille du texte"), ("es", "Tema, acento y tamaño de texto"),
                ("pt", "Tema, destaque e tamanho do texto"), ("it", "Tema, accento e dimensione testo"),
                ("zh-CN", "默认主题、强调色与字号"), ("zh-TW", "預設主題、強調色與字級"),
                ("ko", "기본 테마, 강조색, 글자 크기"), ("ru", "Тема, акцент и размер текста")),
            ["set.display"] = Lang(("en", "Display"), ("ja", "ディスプレイ"), ("de", "Anzeige"), ("fr", "Affichage"),
                ("es", "Pantalla"), ("pt", "Tela"), ("it", "Display"), ("zh-CN", "显示"), ("zh-TW", "顯示"),
                ("ko", "디스플레이"), ("ru", "Экран")),
            ["set.display.blurb"] = Lang(("en", "Size, miniature, case, layout, and brightness"),
                ("ja", "サイズ、ミニ、ケース、レイアウト、明るさ"), ("de", "Größe, Mini, Gehäuse, Layout und Helligkeit"),
                ("fr", "Taille, mini, coque, disposition et luminosité"),
                ("es", "Tamaño, mini, carcasa, diseño y brillo"),
                ("pt", "Tamanho, mini, capa, layout e brilho"),
                ("it", "Dimensione, mini, cover, layout e luminosità"),
                ("zh-CN", "尺寸、迷你、外壳、布局与亮度"), ("zh-TW", "尺寸、迷你、外殼、版面與亮度"),
                ("ko", "크기, 미니, 케이스, 레이아웃, 밝기"), ("ru", "Размер, мини, корпус, сетка и яркость")),
            ["set.wallpaper"] = Lang(("en", "Wallpaper"), ("ja", "壁紙"), ("de", "Hintergrund"), ("fr", "Fond d’écran"),
                ("es", "Fondo"), ("pt", "Papel de parede"), ("it", "Sfondo"), ("zh-CN", "壁纸"), ("zh-TW", "桌布"),
                ("ko", "배경화면"), ("ru", "Обои")),
            ["set.wallpaper.blurb"] = Lang(("en", "Bundled plates and Gallery background"),
                ("ja", "付属プレートとギャラリー背景"), ("de", "Mitgelieferte Platten und Galerie-Hintergrund"),
                ("fr", "Fonds inclus et fond Galerie"), ("es", "Fondos incluidos y fondo de Galería"),
                ("pt", "Fundos inclusos e fundo da Galeria"), ("it", "Sfondi inclusi e sfondo Galleria"),
                ("zh-CN", "自带壁纸与相册背景"), ("zh-TW", "內建桌布與相簿背景"),
                ("ko", "기본 배경과 갤러리 배경"), ("ru", "Встроенные фоны и фон Галереи")),
            ["set.dim"] = Lang(("en", "Dim"), ("ja", "減光"), ("de", "Dimmen"), ("fr", "Atténuer"),
                ("es", "Atenuar"), ("pt", "Escurecer"), ("it", "Attenua"), ("zh-CN", "调暗"), ("zh-TW", "調暗"),
                ("ko", "어둡게"), ("ru", "Затемнение")),
            ["set.dim.blurb"] = Lang(("en", "Light, medium, or dark overlay"),
                ("ja", "明るい、中間、暗いオーバーレイ"), ("de", "Helle, mittlere oder dunkle Überlagerung"),
                ("fr", "Calque clair, moyen ou sombre"), ("es", "Capa clara, media u oscura"),
                ("pt", "Sobreposição clara, média ou escura"), ("it", "Sovrapposizione chiara, media o scura"),
                ("zh-CN", "浅、中、深遮罩"), ("zh-TW", "淺、中、深遮罩"),
                ("ko", "밝은, 중간, 어두운 오버레이"), ("ru", "Светлая, средняя или тёмная вуаль")),
            ["set.homescreen"] = Lang(("en", "Home screen"), ("ja", "ホーム画面"), ("de", "Startbildschirm"),
                ("fr", "Écran d’accueil"), ("es", "Pantalla de inicio"), ("pt", "Tela inicial"),
                ("it", "Schermata Home"), ("zh-CN", "主屏幕"), ("zh-TW", "主畫面"),
                ("ko", "홈 화면"), ("ru", "Домашний экран")),
            ["set.homescreen.blurb"] = Lang(("en", "Greeting banner and extra screens"),
                ("ja", "挨拶バナーと追加画面"), ("de", "Begrüßungsbanner und Extra-Bildschirme"),
                ("fr", "Bannière d’accueil et écrans extra"), ("es", "Banner de saludo y pantallas extra"),
                ("pt", "Faixa de saudação e telas extras"), ("it", "Banner di saluto e schermate extra"),
                ("zh-CN", "问候横幅与额外屏幕"), ("zh-TW", "問候橫幅與額外畫面"),
                ("ko", "인사 배너와 추가 화면"), ("ru", "Приветствие и доп. экраны")),
            ["set.statusbar"] = Lang(("en", "Status bar"), ("ja", "ステータスバー"), ("de", "Statusleiste"),
                ("fr", "Barre d’état"), ("es", "Barra de estado"), ("pt", "Barra de status"),
                ("it", "Barra di stato"), ("zh-CN", "状态栏"), ("zh-TW", "狀態列"),
                ("ko", "상태 표시줄"), ("ru", "Строка состояния")),
            ["set.statusbar.blurb"] = Lang(("en", "World name and status icons"),
                ("ja", "ワールド名とステータスアイコン"), ("de", "Weltname und Statussymbole"),
                ("fr", "Nom du monde et icônes d’état"), ("es", "Mundo e iconos de estado"),
                ("pt", "Mundo e ícones de status"), ("it", "Mondo e icone di stato"),
                ("zh-CN", "世界名与状态图标"), ("zh-TW", "世界名與狀態圖示"),
                ("ko", "월드 이름과 상태 아이콘"), ("ru", "Мир и значки статуса")),
            ["set.tuner"] = Lang(("en", "Interactive tuner"), ("ja", "インタラクティブ調整"),
                ("de", "Interaktiver Tuner"), ("fr", "Réglage interactif"),
                ("es", "Ajuste interactivo"), ("pt", "Ajuste interativo"), ("it", "Regolazione interattiva"),
                ("zh-CN", "交互调节"), ("zh-TW", "互動調節"), ("ko", "인터랙티브 튜너"), ("ru", "Интерактивная настройка")),
            ["set.tuner.blurb"] = Lang(("en", "Touch the phone preview to edit parts"),
                ("ja", "プレビューをタッチして各部を編集"), ("de", "Vorschau berühren, um Teile zu ändern"),
                ("fr", "Touchez l’aperçu pour modifier des parties"),
                ("es", "Toca la vista previa para editar partes"),
                ("pt", "Toque a prévia para editar partes"),
                ("it", "Tocca l’anteprima per modificare le parti"),
                ("zh-CN", "点按预览以编辑部件"), ("zh-TW", "點按預覽以編輯部件"),
                ("ko", "미리보기를 눌러 부분을 편집"), ("ru", "Коснитесь превью, чтобы править части")),
            ["set.motion"] = Lang(("en", "Reduce motion"), ("ja", "動きを減らす"), ("de", "Bewegung reduzieren"),
                ("fr", "Réduire les animations"), ("es", "Reducir movimiento"), ("pt", "Reduzir movimento"),
                ("it", "Riduci movimento"), ("zh-CN", "减少动态"), ("zh-TW", "減少動態"),
                ("ko", "움직임 줄이기"), ("ru", "Меньше анимации")),
            ["set.motion.hint"] = Lang(("en", "Limit motion on the screen."),
                ("ja", "画面上の動きを抑えます。"), ("de", "Bewegung auf dem Bildschirm begrenzen."),
                ("fr", "Limiter le mouvement à l’écran."), ("es", "Limita el movimiento en pantalla."),
                ("pt", "Limita o movimento na tela."), ("it", "Limita il movimento sullo schermo."),
                ("zh-CN", "限制屏幕上的动态。"), ("zh-TW", "限制畫面上的動態。"),
                ("ko", "화면 움직임을 줄입니다."), ("ru", "Ограничить движение на экране.")),
            ["set.fight.stay"] = Lang(("en", "Stay on screen"), ("ja", "画面に残す"), ("de", "Auf dem Bildschirm bleiben"),
                ("fr", "Rester à l’écran"), ("es", "Quedarse en pantalla"), ("pt", "Ficar na tela"),
                ("it", "Resta a schermo"), ("zh-CN", "保持在屏幕上"), ("zh-TW", "保持在畫面上"),
                ("ko", "화면에 유지"), ("ru", "Оставить на экране")),
            ["set.fight.stay.hint"] = Lang(("en", "Keep the phone up in combat."),
                ("ja", "戦闘中も端末を表示します。"), ("de", "Telefon im Kampf offen lassen."),
                ("fr", "Garder le téléphone ouvert en combat."), ("es", "Mantén el teléfono en combate."),
                ("pt", "Mantenha o telefone no combate."), ("it", "Tieni il telefono aperto in combattimento."),
                ("zh-CN", "战斗中保持手机打开。"), ("zh-TW", "戰鬥中保持手機開啟。"),
                ("ko", "전투 중에도 휴대폰을 켭니다."), ("ru", "Не убирать телефон в бою.")),
            ["set.fight.pocket"] = Lang(("en", "Minimize in combat"), ("ja", "戦闘中は最小化"),
                ("de", "Im Kampf minimieren"), ("fr", "Réduire en combat"),
                ("es", "Minimizar en combate"), ("pt", "Minimizar no combate"), ("it", "Riduci in combattimento"),
                ("zh-CN", "战斗中最小化"), ("zh-TW", "戰鬥中最小化"),
                ("ko", "전투 중 최소화"), ("ru", "Свернуть в бою")),
            ["set.fight.pocket.hint"] = Lang(("en", "Minimize the phone in combat."),
                ("ja", "戦闘中は端末を最小化します。"), ("de", "Telefon im Kampf minimieren."),
                ("fr", "Réduire le téléphone en combat."), ("es", "Minimiza el teléfono en combate."),
                ("pt", "Minimiza o telefone no combate."), ("it", "Riduci il telefono in combattimento."),
                ("zh-CN", "战斗中将手机最小化。"), ("zh-TW", "戰鬥中將手機最小化。"),
                ("ko", "전투 중 휴대폰을 최소화합니다."), ("ru", "Свернуть телефон в бою.")),
            ["set.fight.hide"] = Lang(("en", "Hide in combat"), ("ja", "戦闘中は隠す"), ("de", "Im Kampf ausblenden"),
                ("fr", "Masquer en combat"), ("es", "Ocultar en combate"), ("pt", "Ocultar no combate"),
                ("it", "Nascondi in combattimento"), ("zh-CN", "战斗中隐藏"), ("zh-TW", "戰鬥中隱藏"),
                ("ko", "전투 중 숨기기"), ("ru", "Скрыть в бою")),
            ["set.fight.hide.hint"] = Lang(("en", "Hide the phone in combat."),
                ("ja", "戦闘中は端末を隠します。"), ("de", "Telefon im Kampf ausblenden."),
                ("fr", "Masquer le téléphone en combat."), ("es", "Oculta el teléfono en combate."),
                ("pt", "Oculta o telefone no combate."), ("it", "Nascondi il telefono in combattimento."),
                ("zh-CN", "战斗中隐藏手机。"), ("zh-TW", "戰鬥中隱藏手機。"),
                ("ko", "전투 중 휴대폰을 숨깁니다."), ("ru", "Скрыть телефон в бою.")),
            ["set.brightness"] = Lang(("en", "Brightness"), ("ja", "明るさ"), ("de", "Helligkeit"),
                ("fr", "Luminosité"), ("es", "Brillo"), ("pt", "Brilho"), ("it", "Luminosità"),
                ("zh-CN", "亮度"), ("zh-TW", "亮度"), ("ko", "밝기"), ("ru", "Яркость")),
            ["set.size"] = Lang(("en", "Phone size"), ("ja", "端末サイズ"), ("de", "Telefongröße"),
                ("fr", "Taille du téléphone"), ("es", "Tamaño del teléfono"), ("pt", "Tamanho do telefone"),
                ("it", "Dimensione telefono"), ("zh-CN", "手机尺寸"), ("zh-TW", "手機尺寸"),
                ("ko", "휴대폰 크기"), ("ru", "Размер телефона")),
            ["set.feed.say"] = Lang(("en", "Show Say"), ("ja", "Sayを表示"), ("de", "Say anzeigen"),
                ("fr", "Afficher Say"), ("es", "Mostrar Say"), ("pt", "Mostrar Say"), ("it", "Mostra Say"),
                ("zh-CN", "显示说话"), ("zh-TW", "顯示說話"), ("ko", "Say 표시"), ("ru", "Показать Say")),
            ["set.feed.say.hint"] = Lang(("en", "Nearby Say lines in Feed."),
                ("ja", "近くのSayをフィードに表示。"), ("de", "Nahe Say-Zeilen im Feed."),
                ("fr", "Lignes Say proches dans le fil."), ("es", "Líneas Say cercanas en el feed."),
                ("pt", "Linhas Say próximas no feed."), ("it", "Righe Say vicine nel feed."),
                ("zh-CN", "在动态中显示附近说话。"), ("zh-TW", "在動態中顯示附近說話。"),
                ("ko", "근처 Say를 피드에 표시."), ("ru", "Ближний Say в ленте.")),
            ["set.feed.shout"] = Lang(("en", "Show Shout"), ("ja", "Shoutを表示"), ("de", "Shout anzeigen"),
                ("fr", "Afficher Shout"), ("es", "Mostrar Shout"), ("pt", "Mostrar Shout"), ("it", "Mostra Shout"),
                ("zh-CN", "显示呼喊"), ("zh-TW", "顯示呼喊"), ("ko", "Shout 표시"), ("ru", "Показать Shout")),
            ["set.feed.shout.hint"] = Lang(("en", "Shout lines in Feed."),
                ("ja", "Shoutをフィードに表示。"), ("de", "Shout-Zeilen im Feed."),
                ("fr", "Lignes Shout dans le fil."), ("es", "Líneas Shout en el feed."),
                ("pt", "Linhas Shout no feed."), ("it", "Righe Shout nel feed."),
                ("zh-CN", "在动态中显示呼喊。"), ("zh-TW", "在動態中顯示呼喊。"),
                ("ko", "Shout를 피드에 표시."), ("ru", "Shout в ленте.")),
            ["set.feed.yell"] = Lang(("en", "Show Yell"), ("ja", "Yellを表示"), ("de", "Yell anzeigen"),
                ("fr", "Afficher Yell"), ("es", "Mostrar Yell"), ("pt", "Mostrar Yell"), ("it", "Mostra Yell"),
                ("zh-CN", "显示大喊"), ("zh-TW", "顯示大喊"), ("ko", "Yell 표시"), ("ru", "Показать Yell")),
            ["set.feed.yell.hint"] = Lang(("en", "Yell lines in Feed."),
                ("ja", "Yellをフィードに表示。"), ("de", "Yell-Zeilen im Feed."),
                ("fr", "Lignes Yell dans le fil."), ("es", "Líneas Yell en el feed."),
                ("pt", "Linhas Yell no feed."), ("it", "Righe Yell nel feed."),
                ("zh-CN", "在动态中显示大喊。"), ("zh-TW", "在動態中顯示大喊。"),
                ("ko", "Yell을 피드에 표시."), ("ru", "Yell в ленте.")),
            ["set.feed.party"] = Lang(("en", "Show Party"), ("ja", "パーティを表示"), ("de", "Gruppe anzeigen"),
                ("fr", "Afficher l’équipe"), ("es", "Mostrar grupo"), ("pt", "Mostrar grupo"), ("it", "Mostra party"),
                ("zh-CN", "显示小队"), ("zh-TW", "顯示小隊"), ("ko", "파티 표시"), ("ru", "Показать группу")),
            ["set.feed.party.hint"] = Lang(("en", "Party lines in Feed."),
                ("ja", "パーティ発言をフィードに表示。"), ("de", "Gruppenzeilen im Feed."),
                ("fr", "Lignes d’équipe dans le fil."), ("es", "Líneas de grupo en el feed."),
                ("pt", "Linhas do grupo no feed."), ("it", "Righe party nel feed."),
                ("zh-CN", "在动态中显示小队。"), ("zh-TW", "在動態中顯示小隊。"),
                ("ko", "파티 대화를 피드에 표시."), ("ru", "Группа в ленте.")),
            ["set.quiet"] = Lang(("en", "Do not disturb"), ("ja", "通知オフ"), ("de", "Nicht stören"),
                ("fr", "Ne pas déranger"), ("es", "No molestar"), ("pt", "Não perturbe"), ("it", "Non disturbare"),
                ("zh-CN", "勿扰"), ("zh-TW", "勿擾"), ("ko", "방해 금지"), ("ru", "Не беспокоить")),
            ["set.quiet.hint"] = Lang(("en", "Silence alerts on this phone."),
                ("ja", "この端末の通知を消音します。"), ("de", "Hinweise auf diesem Telefon stummschalten."),
                ("fr", "Couper les alertes de ce téléphone."), ("es", "Silencia avisos en este teléfono."),
                ("pt", "Silencia alertas neste telefone."), ("it", "Silenzia gli avvisi su questo telefono."),
                ("zh-CN", "静音此手机的提醒。"), ("zh-TW", "靜音此手機的提醒。"),
                ("ko", "이 휴대폰의 알림을 끕니다."), ("ru", "Отключить оповещения на этом телефоне.")),
            ["set.quiet.duty"] = Lang(("en", "Do not disturb in duties"), ("ja", "コンテンツ中は通知オフ"),
                ("de", "Nicht stören in Duties"), ("fr", "Ne pas déranger en mission"),
                ("es", "No molestar en duties"), ("pt", "Não perturbe em duties"),
                ("it", "Non disturbare in missione"), ("zh-CN", "副本中勿扰"), ("zh-TW", "副本中勿擾"),
                ("ko", "임무 중 방해 금지"), ("ru", "Не беспокоить в данжах")),
            ["set.quiet.duty.hint"] = Lang(("en", "Silence automatically while you are in a duty."),
                ("ja", "コンテンツ中は自動で消音します。"), ("de", "Automatisch stumm in einer Duty."),
                ("fr", "Coupe automatiquement en mission."), ("es", "Silencia automáticamente en un duty."),
                ("pt", "Silencia automaticamente em uma duty."),
                ("it", "Silenzia automaticamente in missione."),
                ("zh-CN", "进入副本时自动静音。"), ("zh-TW", "進入副本時自動靜音。"),
                ("ko", "임무 중 자동으로 음소거합니다."), ("ru", "Автотишина в данже.")),
            ["set.badges"] = Lang(("en", "App icon badges"), ("ja", "アプリアイコンバッジ"),
                ("de", "App-Markierungen"), ("fr", "Badges d’icônes"),
                ("es", "Distintivos de iconos"), ("pt", "Selos de ícones"), ("it", "Badge delle icone"),
                ("zh-CN", "应用角标"), ("zh-TW", "應用標記"), ("ko", "앱 아이콘 배지"), ("ru", "Значки на иконках")),
            ["set.badges.hint"] = Lang(("en", "Show marks on the status bar."),
                ("ja", "ステータスバーにマークを表示。"), ("de", "Markierungen in der Statusleiste zeigen."),
                ("fr", "Afficher les marques dans la barre d’état."),
                ("es", "Muestra marcas en la barra de estado."),
                ("pt", "Mostra marcas na barra de status."),
                ("it", "Mostra i contrassegni nella barra di stato."),
                ("zh-CN", "在状态栏显示标记。"), ("zh-TW", "在狀態列顯示標記。"),
                ("ko", "상태 표시줄에 표시합니다."), ("ru", "Показывать метки в строке состояния.")),
            ["set.wake.calls"] = Lang(("en", "Wake for calls"), ("ja", "着信で起動"), ("de", "Bei Anrufen aufwecken"),
                ("fr", "Réveiller pour les appels"), ("es", "Activar por llamadas"),
                ("pt", "Despertar para chamadas"), ("it", "Riattiva per le chiamate"),
                ("zh-CN", "来电唤醒"), ("zh-TW", "來電喚醒"), ("ko", "통화 시 깨우기"), ("ru", "Будить для звонков")),
            ["set.wake.calls.hint"] = Lang(("en", "Wake the minimized phone for a call."),
                ("ja", "最小化中でも着信で起動します。"), ("de", "Minimiertes Telefon bei einem Anruf aufwecken."),
                ("fr", "Réveiller le téléphone réduit pour un appel."),
                ("es", "Activa el teléfono minimizado por una llamada."),
                ("pt", "Acorda o telefone minimizado para uma chamada."),
                ("it", "Riattiva il telefono ridotto per una chiamata."),
                ("zh-CN", "最小化时来电唤醒手机。"), ("zh-TW", "最小化時來電喚醒手機。"),
                ("ko", "최소화된 휴대폰을 통화로 깨웁니다."), ("ru", "Разбудить свёрнутый телефон для звонка.")),
            ["set.portraits"] = Lang(("en", "Keep phone on in portraits"),
                ("ja", "ポートレート中も表示"), ("de", "Bei Porträts offen lassen"),
                ("fr", "Garder ouvert en portraits"), ("es", "Mantener en retratos"),
                ("pt", "Manter em retratos"), ("it", "Tieni aperto nei ritratti"),
                ("zh-CN", "肖像中保持开启"), ("zh-TW", "肖像中保持開啟"),
                ("ko", "초상 중에도 켜 두기"), ("ru", "Не убирать в портретах")),
            ["set.portraits.hint"] = Lang(("en", "Stay on screen during portraits."),
                ("ja", "ポートレート中も画面に残します。"), ("de", "Während Porträts auf dem Bildschirm bleiben."),
                ("fr", "Rester à l’écran pendant les portraits."),
                ("es", "Permanece en pantalla durante retratos."),
                ("pt", "Permanece na tela durante retratos."),
                ("it", "Resta a schermo durante i ritratti."),
                ("zh-CN", "肖像期间留在屏幕上。"), ("zh-TW", "肖像期間留在畫面上。"),
                ("ko", "초상 중에도 화면에 둡니다."), ("ru", "Оставить на экране в портретах.")),
            ["set.cutscenes"] = Lang(("en", "Hide during cutscenes"), ("ja", "カットシーン中は隠す"),
                ("de", "Bei Zwischensequenzen ausblenden"), ("fr", "Masquer pendant les cinématiques"),
                ("es", "Ocultar en cinemáticas"), ("pt", "Ocultar em cenas"),
                ("it", "Nascondi durante le scene"), ("zh-CN", "过场中隐藏"), ("zh-TW", "過場中隱藏"),
                ("ko", "컷신 중 숨기기"), ("ru", "Скрывать в катсценах")),
            ["set.cutscenes.hint"] = Lang(("en", "Put the phone away for cutscenes."),
                ("ja", "カットシーン中は端末をしまいます。"), ("de", "Telefon bei Zwischensequenzen wegstecken."),
                ("fr", "Ranger le téléphone pendant les cinématiques."),
                ("es", "Guarda el teléfono en las cinemáticas."),
                ("pt", "Guarda o telefone nas cenas."),
                ("it", "Metti via il telefono durante le scene."),
                ("zh-CN", "过场时收起手机。"), ("zh-TW", "過場時收起手機。"),
                ("ko", "컷신 중 휴대폰을 넣습니다."), ("ru", "Убрать телефон в катсцене.")),
            ["set.chat.e2e"] = Lang(("en", "Seal Pearlgate chats"), ("ja", "Pearlgate会話を封印"),
                ("de", "Pearlgate-Chats versiegeln"), ("fr", "Sceller les chats Pearlgate"),
                ("es", "Sellar chats de Pearlgate"), ("pt", "Selar chats Pearlgate"),
                ("it", "Sigilla le chat Pearlgate"), ("zh-CN", "封印 Pearlgate 聊天"),
                ("zh-TW", "封印 Pearlgate 聊天"), ("ko", "Pearlgate 채팅 봉인"),
                ("ru", "Печатать чаты Pearlgate")),
            ["set.chat.e2e.hint"] = Lang(
                ("en", "Encrypt bodies when everyone in the room has a Linkpearl key. Otherwise send plaintext."),
                ("ja", "全員がLinkpearl鍵を持つ部屋だけ本文を暗号化。欠けていれば平文のまま送ります。"),
                ("de", "Verschlüsselt Texte, wenn alle im Raum einen Linkpearl-Schlüssel haben. Sonst Klartext."),
                ("fr", "Chiffre le texte si tout le monde a une clé Linkpearl. Sinon, envoi en clair."),
                ("es", "Cifra el texto si todos tienen una clave Linkpearl. Si no, se envía en claro."),
                ("pt", "Cifra o texto se todos tiverem uma chave Linkpearl. Senão, envia em claro."),
                ("it", "Cifra il testo se tutti hanno una chiave Linkpearl. Altrimenti resta in chiaro."),
                ("zh-CN", "仅当房间内都有 Linkpearl 密钥时加密正文，否则仍发明文。"),
                ("zh-TW", "僅當房間內都有 Linkpearl 金鑰時加密正文，否則仍發明文。"),
                ("ko", "모두 Linkpearl 키가 있을 때만 본문을 암호화합니다. 없으면 평문으로 보냅니다."),
                ("ru", "Шифрует текст, если у всех в комнате есть ключ Linkpearl. Иначе — открытый текст.")),
            ["set.hour12.hint"] = Lang(("en", "1:00 PM."), ("ja", "午後1:00。"), ("de", "13:00 als 1:00 PM."),
                ("fr", "13:00 en 1:00 PM."), ("es", "1:00 p. m."), ("pt", "1:00 PM."),
                ("it", "1:00 PM."), ("zh-CN", "下午 1:00。"), ("zh-TW", "下午 1:00。"),
                ("ko", "오후 1:00."), ("ru", "1:00 PM.")),
            ["set.hour24.hint"] = Lang(("en", "13:00."), ("ja", "13:00。"), ("de", "13:00."),
                ("fr", "13:00."), ("es", "13:00."), ("pt", "13:00."), ("it", "13:00."),
                ("zh-CN", "13:00。"), ("zh-TW", "13:00。"), ("ko", "13:00."), ("ru", "13:00.")),
            ["set.clock.local.hint"] = Lang(("en", "Your real-world clock."),
                ("ja", "現実世界の時計。"), ("de", "Deine reale Uhr."),
                ("fr", "Votre horloge réelle."), ("es", "Tu reloj del mundo real."),
                ("pt", "Seu relógio do mundo real."), ("it", "Il tuo orologio reale."),
                ("zh-CN", "现实世界时钟。"), ("zh-TW", "現實世界時鐘。"),
                ("ko", "현실 세계 시계."), ("ru", "Часы реального мира.")),
            ["set.clock.eorzea.hint"] = Lang(("en", "In-world clock."),
                ("ja", "ゲーム内の時計。"), ("de", "Uhr in der Welt."),
                ("fr", "Horloge du monde."), ("es", "Reloj del mundo."),
                ("pt", "Relógio do mundo."), ("it", "Orologio del mondo."),
                ("zh-CN", "游戏世界时钟。"), ("zh-TW", "遊戲世界時鐘。"),
                ("ko", "게임 세계 시계."), ("ru", "Игровые часы.")),
            ["set.clock.both.hint"] = Lang(("en", "Local and Eorzea time together."),
                ("ja", "現地時間とエオルゼア時間。"), ("de", "Ortszeit und Eorzea-Zeit zusammen."),
                ("fr", "Heure locale et d’Éorzéa ensemble."),
                ("es", "Hora local y de Eorzea juntas."),
                ("pt", "Hora local e de Eorzea juntas."),
                ("it", "Ora locale e di Eorzea insieme."),
                ("zh-CN", "同时显示本地与艾欧泽亚时间。"), ("zh-TW", "同時顯示當地與艾歐澤亞時間。"),
                ("ko", "현지 시간과 에오르제아 시간."), ("ru", "Местное и эорзейское время вместе.")),
            ["set.vol.listen"] = Lang(("en", "Listen volume"), ("ja", "再生音量"), ("de", "Hörlautstärke"),
                ("fr", "Volume d’écoute"), ("es", "Volumen de escucha"), ("pt", "Volume de escuta"),
                ("it", "Volume di ascolto"), ("zh-CN", "收听音量"), ("zh-TW", "收聽音量"),
                ("ko", "듣기 음량"), ("ru", "Громкость прослушивания")),
            ["set.vol.mic"] = Lang(("en", "Microphone volume"), ("ja", "マイク音量"), ("de", "Mikrofonlautstärke"),
                ("fr", "Volume du micro"), ("es", "Volumen del micrófono"), ("pt", "Volume do microfone"),
                ("it", "Volume microfono"), ("zh-CN", "麦克风音量"), ("zh-TW", "麥克風音量"),
                ("ko", "마이크 음량"), ("ru", "Громкость микрофона")),
            ["set.sounds.mute"] = Lang(("en", "Mute phone sounds"), ("ja", "端末音を消す"),
                ("de", "Telefontöne stummschalten"), ("fr", "Couper les sons du téléphone"),
                ("es", "Silenciar sonidos del teléfono"), ("pt", "Silenciar sons do telefone"),
                ("it", "Silenzia i suoni del telefono"), ("zh-CN", "静音手机声音"), ("zh-TW", "靜音手機聲音"),
                ("ko", "휴대폰 소리 끄기"), ("ru", "Выключить звуки телефона")),
            ["set.world"] = Lang(("en", "Show world name"), ("ja", "ワールド名を表示"),
                ("de", "Weltname anzeigen"), ("fr", "Afficher le nom du monde"),
                ("es", "Mostrar mundo"), ("pt", "Mostrar mundo"), ("it", "Mostra il mondo"),
                ("zh-CN", "显示世界名"), ("zh-TW", "顯示世界名"), ("ko", "월드 이름 표시"), ("ru", "Показать мир")),
            ["set.world.hint"] = Lang(("en", "World name in the status bar."),
                ("ja", "ステータスバーにワールド名。"), ("de", "Weltname in der Statusleiste."),
                ("fr", "Nom du monde dans la barre d’état."),
                ("es", "Nombre del mundo en la barra de estado."),
                ("pt", "Nome do mundo na barra de status."),
                ("it", "Nome del mondo nella barra di stato."),
                ("zh-CN", "状态栏显示世界名。"), ("zh-TW", "狀態列顯示世界名。"),
                ("ko", "상태 표시줄에 월드 이름."), ("ru", "Имя мира в строке состояния.")),
            ["set.icons"] = Lang(("en", "Show status icons"), ("ja", "ステータスアイコンを表示"),
                ("de", "Statussymbole anzeigen"), ("fr", "Afficher les icônes d’état"),
                ("es", "Mostrar iconos de estado"), ("pt", "Mostrar ícones de status"),
                ("it", "Mostra icone di stato"), ("zh-CN", "显示状态图标"), ("zh-TW", "顯示狀態圖示"),
                ("ko", "상태 아이콘 표시"), ("ru", "Показать значки статуса")),
            ["set.icons.hint"] = Lang(("en", "Signal, wifi, and battery."),
                ("ja", "電波、Wi-Fi、バッテリー。"), ("de", "Signal, WLAN und Akku."),
                ("fr", "Signal, wifi et batterie."), ("es", "Señal, wifi y batería."),
                ("pt", "Sinal, wifi e bateria."), ("it", "Segnale, wifi e batteria."),
                ("zh-CN", "信号、无线与电量。"), ("zh-TW", "訊號、無線與電量。"),
                ("ko", "신호, 와이파이, 배터리."), ("ru", "Сигнал, wifi и батарея.")),
            ["set.lock.pos"] = Lang(("en", "Lock position"), ("ja", "位置を固定"), ("de", "Position sperren"),
                ("fr", "Verrouiller la position"), ("es", "Bloquear posición"), ("pt", "Travar posição"),
                ("it", "Blocca posizione"), ("zh-CN", "锁定位置"), ("zh-TW", "鎖定位置"),
                ("ko", "위치 잠금"), ("ru", "Закрепить положение")),
            ["set.lock.pos.hint"] = Lang(("en", "Keep the phone from sliding."),
                ("ja", "端末が動かないようにします。"), ("de", "Verhindert, dass das Telefon verrutscht."),
                ("fr", "Empêche le téléphone de glisser."), ("es", "Evita que el teléfono se deslice."),
                ("pt", "Impede o telefone de deslizar."), ("it", "Impedisce al telefono di scivolare."),
                ("zh-CN", "防止手机滑动。"), ("zh-TW", "防止手機滑動。"),
                ("ko", "휴대폰이 밀리지 않게 합니다."), ("ru", "Не давать телефону сдвигаться.")),
            ["set.lock.tab"] = Lang(("en", "Show lock button"), ("ja", "ロックボタンを表示"),
                ("de", "Sperrknopf anzeigen"), ("fr", "Afficher le bouton de verrou"),
                ("es", "Mostrar botón de bloqueo"), ("pt", "Mostrar botão de bloqueio"),
                ("it", "Mostra il pulsante di blocco"), ("zh-CN", "显示锁定按钮"), ("zh-TW", "顯示鎖定按鈕"),
                ("ko", "잠금 버튼 표시"), ("ru", "Показать кнопку блокировки")),
            ["set.lock.tab.hint"] = Lang(("en", "Show the lock tab on the screen."),
                ("ja", "画面にロックタブを表示。"), ("de", "Sperrreiter auf dem Bildschirm zeigen."),
                ("fr", "Afficher l’onglet de verrou à l’écran."),
                ("es", "Muestra la pestaña de bloqueo en pantalla."),
                ("pt", "Mostra a aba de bloqueio na tela."),
                ("it", "Mostra la linguetta di blocco sullo schermo."),
                ("zh-CN", "在屏幕上显示锁定标签。"), ("zh-TW", "在畫面上顯示鎖定分頁。"),
                ("ko", "화면에 잠금 탭을 표시."), ("ru", "Показать вкладку блокировки на экране.")),
            ["set.silent"] = Lang(("en", "Silent"), ("ja", "サイレント"), ("de", "Stumm"), ("fr", "Silencieux"),
                ("es", "Silencio"), ("pt", "Silencioso"), ("it", "Silenzioso"), ("zh-CN", "静音"), ("zh-TW", "靜音"),
                ("ko", "무음"), ("ru", "Тихий")),
            ["set.silent.hint"] = Lang(("en", "Mute phone sounds."),
                ("ja", "端末の音を消します。"), ("de", "Telefontöne stummschalten."),
                ("fr", "Couper les sons du téléphone."), ("es", "Silencia los sonidos del teléfono."),
                ("pt", "Silencia os sons do telefone."), ("it", "Silenzia i suoni del telefono."),
                ("zh-CN", "静音手机声音。"), ("zh-TW", "靜音手機聲音。"),
                ("ko", "휴대폰 소리를 끕니다."), ("ru", "Выключить звуки телефона.")),
            ["set.silent.duty"] = Lang(("en", "Silent in duties"), ("ja", "コンテンツ中は消音"),
                ("de", "Stumm in Duties"), ("fr", "Silencieux en mission"),
                ("es", "Silencio en duties"), ("pt", "Silencioso em duties"),
                ("it", "Silenzioso in missione"), ("zh-CN", "副本中静音"), ("zh-TW", "副本中靜音"),
                ("ko", "임무 중 무음"), ("ru", "Тихий в данжах")),
            ["set.wake.mini"] = Lang(("en", "Wake when minimized"), ("ja", "最小化時に起動"),
                ("de", "Aufwecken wenn minimiert"), ("fr", "Réveiller si réduit"),
                ("es", "Activar si está minimizado"), ("pt", "Acordar se minimizado"),
                ("it", "Riattiva se ridotto"), ("zh-CN", "最小化时唤醒"), ("zh-TW", "最小化時喚醒"),
                ("ko", "최소화 시 깨우기"), ("ru", "Будить в свёрнутом виде")),
            ["set.wake.mini.hint"] = Lang(("en", "Wake the phone while it is minimized."),
                ("ja", "最小化中でも起動します。"), ("de", "Telefon aufwecken, während es minimiert ist."),
                ("fr", "Réveiller le téléphone lorsqu’il est réduit."),
                ("es", "Activa el teléfono mientras está minimizado."),
                ("pt", "Acorda o telefone enquanto está minimizado."),
                ("it", "Riattiva il telefono mentre è ridotto."),
                ("zh-CN", "最小化时唤醒手机。"), ("zh-TW", "最小化時喚醒手機。"),
                ("ko", "최소화된 동안 휴대폰을 깨웁니다."), ("ru", "Разбудить свёрнутый телефон.")),
            ["set.portraits.open"] = Lang(("en", "Keep open in portraits"),
                ("ja", "ポートレート中も開いたまま"), ("de", "Bei Porträts offen lassen"),
                ("fr", "Garder ouvert en portraits"), ("es", "Mantener abierto en retratos"),
                ("pt", "Manter aberto em retratos"), ("it", "Tieni aperto nei ritratti"),
                ("zh-CN", "肖像中保持打开"), ("zh-TW", "肖像中保持開啟"),
                ("ko", "초상 중 열어 두기"), ("ru", "Не закрывать в портретах")),
            ["shell.quiet"] = Lang(("en", "Quiet"), ("ja", "静音"), ("de", "Ruhig"), ("fr", "Calme"),
                ("es", "Silencio"), ("pt", "Silêncio"), ("it", "Quieto"), ("zh-CN", "静音"), ("zh-TW", "靜音"),
                ("ko", "조용히"), ("ru", "Тихо")),
            ["shell.duties"] = Lang(("en", "Duties"), ("ja", "コンテンツ"), ("de", "Duties"), ("fr", "Missions"),
                ("es", "Duties"), ("pt", "Duties"), ("it", "Missioni"), ("zh-CN", "副本"), ("zh-TW", "副本"),
                ("ko", "임무"), ("ru", "Данжи")),
            ["shell.mini"] = Lang(("en", "Mini"), ("ja", "ミニ"), ("de", "Mini"), ("fr", "Mini"),
                ("es", "Mini"), ("pt", "Mini"), ("it", "Mini"), ("zh-CN", "迷你"), ("zh-TW", "迷你"),
                ("ko", "미니"), ("ru", "Мини")),
            ["shell.gpose"] = Lang(("en", "GPose"), ("ja", "GPose"), ("de", "GPose"), ("fr", "GPose"),
                ("es", "GPose"), ("pt", "GPose"), ("it", "GPose"), ("zh-CN", "GPose"), ("zh-TW", "GPose"),
                ("ko", "GPose"), ("ru", "GPose")),
            ["shell.icons"] = Lang(("en", "Icons"), ("ja", "アイコン"), ("de", "Symbole"), ("fr", "Icônes"),
                ("es", "Iconos"), ("pt", "Ícones"), ("it", "Icone"), ("zh-CN", "图标"), ("zh-TW", "圖示"),
                ("ko", "아이콘"), ("ru", "Значки")),
            ["shell.world"] = Lang(("en", "World"), ("ja", "ワールド"), ("de", "Welt"), ("fr", "Monde"),
                ("es", "Mundo"), ("pt", "Mundo"), ("it", "Mondo"), ("zh-CN", "世界"), ("zh-TW", "世界"),
                ("ko", "월드"), ("ru", "Мир")),
            ["shell.portraits"] = Lang(("en", "Portraits"), ("ja", "ポートレート"), ("de", "Porträts"),
                ("fr", "Portraits"), ("es", "Retratos"), ("pt", "Retratos"), ("it", "Ritratti"),
                ("zh-CN", "肖像"), ("zh-TW", "肖像"), ("ko", "초상"), ("ru", "Портреты")),
            ["shell.scenes"] = Lang(("en", "Scenes"), ("ja", "シーン"), ("de", "Szenen"), ("fr", "Scènes"),
                ("es", "Escenas"), ("pt", "Cenas"), ("it", "Scene"), ("zh-CN", "过场"), ("zh-TW", "過場"),
                ("ko", "장면"), ("ru", "Сцены")),
            ["shell.notifications"] = Lang(("en", "Notifications"), ("ja", "通知"), ("de", "Mitteilungen"),
                ("fr", "Notifications"), ("es", "Notificaciones"), ("pt", "Notificações"),
                ("it", "Notifiche"), ("zh-CN", "通知"), ("zh-TW", "通知"), ("ko", "알림"), ("ru", "Уведомления")),
            ["shell.clear"] = Lang(("en", "Clear all"), ("ja", "すべて消去"), ("de", "Alle löschen"),
                ("fr", "Tout effacer"), ("es", "Borrar todo"), ("pt", "Limpar tudo"), ("it", "Cancella tutto"),
                ("zh-CN", "全部清除"), ("zh-TW", "全部清除"), ("ko", "모두 지우기"), ("ru", "Очистить всё")),
            ["shell.empty"] = Lang(("en", "Nothing waiting."), ("ja", "待機中の通知はありません。"),
                ("de", "Nichts wartet."), ("fr", "Rien en attente."),
                ("es", "Nada en espera."), ("pt", "Nada aguardando."), ("it", "Niente in attesa."),
                ("zh-CN", "没有待处理通知。"), ("zh-TW", "沒有待處理通知。"),
                ("ko", "대기 중인 알림이 없습니다."), ("ru", "Ничего не ждёт.")),
            ["shell.quickapps"] = Lang(("en", "Quick Apps"), ("ja", "クイックアプリ"), ("de", "Schnell-Apps"),
                ("fr", "Apps rapides"), ("es", "Apps rápidas"), ("pt", "Apps rápidos"), ("it", "App rapide"),
                ("zh-CN", "快捷应用"), ("zh-TW", "快捷應用"), ("ko", "빠른 앱"), ("ru", "Быстрые приложения")),
            ["shell.manage.apps"] = Lang(("en", "Manage Apps"), ("ja", "アプリを管理"), ("de", "Apps verwalten"),
                ("fr", "Gérer les applis"), ("es", "Gestionar apps"), ("pt", "Gerenciar apps"),
                ("it", "Gestisci app"), ("zh-CN", "管理应用"), ("zh-TW", "管理應用"),
                ("ko", "앱 관리"), ("ru", "Управление приложениями")),
            ["shell.manage.hint"] = Lang(("en", "Choose which owned apps sit on your screens."),
                ("ja", "画面に置く所有アプリを選びます。"),
                ("de", "Wähle, welche eigenen Apps auf den Bildschirmen liegen."),
                ("fr", "Choisissez quelles applis possédées restent sur vos écrans."),
                ("es", "Elige qué apps propias quedan en tus pantallas."),
                ("pt", "Escolha quais apps próprios ficam nas telas."),
                ("it", "Scegli quali app possedute restano sugli schermi."),
                ("zh-CN", "选择哪些已拥有应用放在屏幕上。"), ("zh-TW", "選擇哪些已擁有應用放在畫面上。"),
                ("ko", "화면에 둘 보유 앱을 고릅니다."), ("ru", "Выберите, какие свои приложения стоят на экранах.")),
            ["shell.search.apps"] = Lang(("en", "Search apps"), ("ja", "アプリを検索"), ("de", "Apps suchen"),
                ("fr", "Rechercher des applis"), ("es", "Buscar apps"), ("pt", "Buscar apps"),
                ("it", "Cerca app"), ("zh-CN", "搜索应用"), ("zh-TW", "搜尋應用"),
                ("ko", "앱 검색"), ("ru", "Искать приложения")),
            ["shell.noplugin"] = Lang(("en", "No plugin"), ("ja", "プラグインなし"), ("de", "Kein Plugin"),
                ("fr", "Pas de plugin"), ("es", "Sin plugin"), ("pt", "Sem plugin"), ("it", "Nessun plugin"),
                ("zh-CN", "无插件"), ("zh-TW", "無外掛"), ("ko", "플러그인 없음"), ("ru", "Нет плагина")),
            ["shell.connected"] = Lang(("en", "Connected"), ("ja", "接続中"), ("de", "Verbunden"),
                ("fr", "Connecté"), ("es", "Conectado"), ("pt", "Conectado"), ("it", "Connesso"),
                ("zh-CN", "已连接"), ("zh-TW", "已連線"), ("ko", "연결됨"), ("ru", "Подключено")),
            ["shell.off"] = Lang(("en", "Off"), ("ja", "オフ"), ("de", "Aus"), ("fr", "Désactivé"),
                ("es", "Apagado"), ("pt", "Desligado"), ("it", "Off"), ("zh-CN", "关闭"), ("zh-TW", "關閉"),
                ("ko", "꺼짐"), ("ru", "Выкл.")),
            ["shell.signing"] = Lang(("en", "Signing in…"), ("ja", "サインイン中…"), ("de", "Anmeldung…"),
                ("fr", "Connexion…"), ("es", "Iniciando sesión…"), ("pt", "Entrando…"), ("it", "Accesso…"),
                ("zh-CN", "正在登录…"), ("zh-TW", "正在登入…"), ("ko", "로그인 중…"), ("ru", "Вход…")),
            ["shell.signed"] = Lang(("en", "Signed in"), ("ja", "サインイン済み"), ("de", "Angemeldet"),
                ("fr", "Connecté"), ("es", "Sesión iniciada"), ("pt", "Conectado"), ("it", "Accesso effettuato"),
                ("zh-CN", "已登录"), ("zh-TW", "已登入"), ("ko", "로그인됨"), ("ru", "Вы вошли")),
            ["shell.entercode"] = Lang(("en", "Confirm XIVAuth"), ("ja", "XIVAuthで確認"), ("de", "XIVAuth bestätigen"),
                ("fr", "Confirmer XIVAuth"), ("es", "Confirmar XIVAuth"), ("pt", "Confirmar XIVAuth"),
                ("it", "Conferma XIVAuth"), ("zh-CN", "在 XIVAuth 确认"), ("zh-TW", "在 XIVAuth 確認"),
                ("ko", "XIVAuth 확인"), ("ru", "Подтвердите XIVAuth")),
            ["shell.signin"] = Lang(("en", "Sign in"), ("ja", "サインイン"), ("de", "Anmelden"),
                ("fr", "Connexion"), ("es", "Iniciar sesión"), ("pt", "Entrar"), ("it", "Accedi"),
                ("zh-CN", "登录"), ("zh-TW", "登入"), ("ko", "로그인"), ("ru", "Войти")),
            ["shell.offline"] = Lang(("en", "Offline"), ("ja", "オフライン"), ("de", "Offline"), ("fr", "Hors ligne"),
                ("es", "Sin conexión"), ("pt", "Offline"), ("it", "Offline"), ("zh-CN", "离线"), ("zh-TW", "離線"),
                ("ko", "오프라인"), ("ru", "Офлайн")),
            ["vybe.tab.home"] = Lang(("en", "Home"), ("ja", "ホーム"), ("de", "Start"), ("fr", "Accueil"),
                ("es", "Inicio"), ("pt", "Início"), ("it", "Home"), ("zh-CN", "主页"), ("zh-TW", "主頁"),
                ("ko", "홈"), ("ru", "Лента")),
            ["vybe.tab.discover"] = Lang(("en", "Discover"), ("ja", "見つける"), ("de", "Entdecken"),
                ("fr", "Découvrir"), ("es", "Descubrir"), ("pt", "Descobrir"), ("it", "Scopri"),
                ("zh-CN", "发现"), ("zh-TW", "探索"), ("ko", "탐색"), ("ru", "Обзор")),
            ["vybe.tab.gallery"] = Lang(("en", "Gallery"), ("ja", "ギャラリー"), ("de", "Galerie"),
                ("fr", "Galerie"), ("es", "Galería"), ("pt", "Galeria"), ("it", "Galleria"),
                ("zh-CN", "图库"), ("zh-TW", "相簿"), ("ko", "갤러리"), ("ru", "Галерея")),
            ["vybe.tab.messages"] = Lang(("en", "Messages"), ("ja", "メッセージ"), ("de", "Nachrichten"),
                ("fr", "Messages"), ("es", "Mensajes"), ("pt", "Mensagens"), ("it", "Messaggi"),
                ("zh-CN", "消息"), ("zh-TW", "訊息"), ("ko", "메시지"), ("ru", "Сообщения")),
            ["vybe.tab.profile"] = Lang(("en", "Profile"), ("ja", "プロフィール"), ("de", "Profil"),
                ("fr", "Profil"), ("es", "Perfil"), ("pt", "Perfil"), ("it", "Profilo"),
                ("zh-CN", "资料"), ("zh-TW", "個人檔案"), ("ko", "프로필"), ("ru", "Профиль")),
            ["vybe.chats"] = Lang(("en", "Chats"), ("ja", "チャット"), ("de", "Chats"), ("fr", "Discussions"),
                ("es", "Chats"), ("pt", "Chats"), ("it", "Chat"), ("zh-CN", "聊天"), ("zh-TW", "聊天"),
                ("ko", "채팅"), ("ru", "Чаты")),
            ["vybe.requests"] = Lang(("en", "Requests"), ("ja", "リクエスト"), ("de", "Anfragen"),
                ("fr", "Demandes"), ("es", "Solicitudes"), ("pt", "Pedidos"), ("it", "Richieste"),
                ("zh-CN", "请求"), ("zh-TW", "請求"), ("ko", "요청"), ("ru", "Запросы")),
            ["vybe.favorites"] = Lang(("en", "Favorites"), ("ja", "お気に入り"), ("de", "Favoriten"),
                ("fr", "Favoris"), ("es", "Favoritos"), ("pt", "Favoritos"), ("it", "Preferiti"),
                ("zh-CN", "收藏"), ("zh-TW", "收藏"), ("ko", "즐겨찾기"), ("ru", "Избранное")),
            ["vybe.welcome"] = Lang(("en", "Welcome back"), ("ja", "おかえり"), ("de", "Willkommen zurück"),
                ("fr", "Bon retour"), ("es", "Bienvenido de nuevo"), ("pt", "Bem-vindo de volta"),
                ("it", "Bentornato"), ("zh-CN", "欢迎回来"), ("zh-TW", "歡迎回來"),
                ("ko", "다시 오신 걸 환영해요"), ("ru", "С возвращением")),
            ["vybe.ready.night"] = Lang(("en", "Ready for the night?"), ("ja", "今夜の準備はできた？"),
                ("de", "Bereit für die Nacht?"), ("fr", "Prêt pour la nuit ?"),
                ("es", "¿Listo para la noche?"), ("pt", "Pronto para a noite?"),
                ("it", "Pronto per la notte?"), ("zh-CN", "准备好今晚了吗？"), ("zh-TW", "準備好今晚了嗎？"),
                ("ko", "오늘 밤 준비됐어?"), ("ru", "Готов к ночи?")),
            ["vybe.ready.day"] = Lang(("en", "Ready to vibe?"), ("ja", "バイブスはいい？"),
                ("de", "Bereit zu vibrieren?"), ("fr", "Prêt à vibrer ?"),
                ("es", "¿Listo para el vibe?"), ("pt", "Pronto para o clima?"),
                ("it", "Pronto a vibrare?"), ("zh-CN", "准备好开始了吗？"), ("zh-TW", "準備好開始了嗎？"),
                ("ko", "분위기 낼 준비됐어?"), ("ru", "Готов поймать вайб?")),
            ["vybe.online"] = Lang(("en", "Online"), ("ja", "オンライン"), ("de", "Online"), ("fr", "En ligne"),
                ("es", "En línea"), ("pt", "Online"), ("it", "Online"), ("zh-CN", "在线"), ("zh-TW", "在線"),
                ("ko", "온라인"), ("ru", "В сети")),
            ["vybe.away"] = Lang(("en", "Away"), ("ja", "離席"), ("de", "Abwesend"), ("fr", "Absent"),
                ("es", "Ausente"), ("pt", "Ausente"), ("it", "Assente"), ("zh-CN", "离开"), ("zh-TW", "離開"),
                ("ko", "자리 비움"), ("ru", "Отошёл")),
            ["weather.unknown"] = Lang(("en", "Unknown skies"), ("ja", "天候不明"), ("de", "Unbekannter Himmel"),
                ("fr", "Ciel inconnu"), ("es", "Cielo desconocido"), ("pt", "Céu desconhecido"),
                ("it", "Cielo sconosciuto"), ("zh-CN", "未知天气"), ("zh-TW", "未知天氣"),
                ("ko", "알 수 없는 하늘"), ("ru", "Небо неизвестно")),
            ["weather.offline"] = Lang(("en", "Not logged in"), ("ja", "未ログイン"), ("de", "Nicht eingeloggt"),
                ("fr", "Hors ligne"), ("es", "Sin sesión"), ("pt", "Sem login"), ("it", "Non connesso"),
                ("zh-CN", "未登录"), ("zh-TW", "未登入"), ("ko", "로그인 안 됨"), ("ru", "Не в игре")),
            ["weather.forecast"] = Lang(("en", "Forecast"), ("ja", "予報"), ("de", "Vorhersage"),
                ("fr", "Prévisions"), ("es", "Pronóstico"), ("pt", "Previsão"), ("it", "Previsioni"),
                ("zh-CN", "预报"), ("zh-TW", "預報"), ("ko", "예보"), ("ru", "Прогноз")),
            ["weather.control"] = Lang(("en", "Control"), ("ja", "操作"), ("de", "Steuerung"),
                ("fr", "Contrôle"), ("es", "Control"), ("pt", "Controle"), ("it", "Controllo"),
                ("zh-CN", "控制"), ("zh-TW", "控制"), ("ko", "제어"), ("ru", "Управление")),
            ["weather.near"] = Lang(("en", "Next few hours"), ("ja", "これから数時間"), ("de", "Die nächsten Stunden"),
                ("fr", "Prochaines heures"), ("es", "Próximas horas"), ("pt", "Próximas horas"),
                ("it", "Prossime ore"), ("zh-CN", "接下来几小时"), ("zh-TW", "接下來幾小時"),
                ("ko", "앞으로 몇 시간"), ("ru", "Ближайшие часы")),
            ["weather.forecast.list"] = Lang(("en", "Forecast"), ("ja", "予報"), ("de", "Vorhersage"),
                ("fr", "Prévisions"), ("es", "Pronóstico"), ("pt", "Previsão"), ("it", "Previsioni"),
                ("zh-CN", "预报"), ("zh-TW", "預報"), ("ko", "예보"), ("ru", "Прогноз")),
            ["weather.now"] = Lang(("en", "Now"), ("ja", "今"), ("de", "Jetzt"), ("fr", "Maintenant"),
                ("es", "Ahora"), ("pt", "Agora"), ("it", "Ora"), ("zh-CN", "现在"), ("zh-TW", "現在"),
                ("ko", "지금"), ("ru", "Сейчас")),
            ["weather.time"] = Lang(("en", "Time"), ("ja", "時間"), ("de", "Zeit"), ("fr", "Heure"),
                ("es", "Hora"), ("pt", "Hora"), ("it", "Ora"), ("zh-CN", "时间"), ("zh-TW", "時間"),
                ("ko", "시간"), ("ru", "Время")),
            ["weather.sky"] = Lang(("en", "Weather"), ("ja", "天候"), ("de", "Wetter"), ("fr", "Météo"),
                ("es", "Clima"), ("pt", "Clima"), ("it", "Meteo"), ("zh-CN", "天气"), ("zh-TW", "天氣"),
                ("ko", "날씨"), ("ru", "Погода")),
            ["weather.natural"] = Lang(("en", "Natural"), ("ja", "自然"), ("de", "Natürlich"), ("fr", "Naturel"),
                ("es", "Natural"), ("pt", "Natural"), ("it", "Naturale"), ("zh-CN", "自然"), ("zh-TW", "自然"),
                ("ko", "자연"), ("ru", "Как есть")),
            ["weather.locked"] = Lang(("en", "Held"), ("ja", "固定"), ("de", "Fixiert"), ("fr", "Fixé"),
                ("es", "Fijo"), ("pt", "Fixo"), ("it", "Fisso"), ("zh-CN", "已锁定"), ("zh-TW", "已鎖定"),
                ("ko", "고정"), ("ru", "Фикс")),
            ["weather.dawn"] = Lang(("en", "Dawn"), ("ja", "夜明け"), ("de", "Morgendämmerung"), ("fr", "Aube"),
                ("es", "Amanecer"), ("pt", "Amanhecer"), ("it", "Alba"), ("zh-CN", "黎明"), ("zh-TW", "黎明"),
                ("ko", "새벽"), ("ru", "Рассвет")),
            ["weather.noon"] = Lang(("en", "Noon"), ("ja", "正午"), ("de", "Mittag"), ("fr", "Midi"),
                ("es", "Mediodía"), ("pt", "Meio-dia"), ("it", "Mezzogiorno"), ("zh-CN", "正午"), ("zh-TW", "正午"),
                ("ko", "정오"), ("ru", "Полдень")),
            ["weather.dusk"] = Lang(("en", "Dusk"), ("ja", "黄昏"), ("de", "Dämmerung"), ("fr", "Crépuscule"),
                ("es", "Anochecer"), ("pt", "Entardecer"), ("it", "Tramonto"), ("zh-CN", "黄昏"), ("zh-TW", "黃昏"),
                ("ko", "황혼"), ("ru", "Сумерки")),
            ["weather.midnight"] = Lang(("en", "Midnight"), ("ja", "夜中"), ("de", "Mitternacht"), ("fr", "Minuit"),
                ("es", "Medianoche"), ("pt", "Meia-noite"), ("it", "Mezzanotte"), ("zh-CN", "午夜"), ("zh-TW", "午夜"),
                ("ko", "자정"), ("ru", "Полночь")),
            ["weather.reset"] = Lang(("en", "Reset"), ("ja", "リセット"), ("de", "Zurücksetzen"), ("fr", "Réinitialiser"),
                ("es", "Restablecer"), ("pt", "Redefinir"), ("it", "Reimposta"), ("zh-CN", "重置"), ("zh-TW", "重設"),
                ("ko", "재설정"), ("ru", "Сброс")),
            ["weather.note"] = Lang(
                ("en", "Only you see this. Fates, mobs, and fishing follow the real sky."),
                ("ja", "あなたにだけ見えます。FATEやモブ、釣りは本物の空に従います。"),
                ("de", "Nur du siehst das. Fates, Mobs und Angeln folgen dem echten Himmel."),
                ("fr", "Vous seul voyez ceci. Fates, mobs et pêche suivent le vrai ciel."),
                ("es", "Solo tú lo ves. Fates, mobs y pesca siguen el cielo real."),
                ("pt", "Só você vê isto. Fates, mobs e pesca seguem o céu real."),
                ("it", "Lo vedi solo tu. Fate, mob e pesca seguono il cielo vero."),
                ("zh-CN", "只有你看得到。FATE、怪物与钓鱼仍跟真实天空。"),
                ("zh-TW", "只有你看得到。FATE、怪物與釣魚仍跟真實天空。"),
                ("ko", "나만 보입니다. 페이트, 몹, 낚시는 실제 하늘을 따릅니다."),
                ("ru", "Это видите только вы. FATE, мобы и рыбалка идут по настоящему небу.")),
            ["weather.note.companion"] = Lang(
                ("en", "Only you see this. Pause Weatherman if the two fight over the sky."),
                ("ja", "あなたにだけ見えます。空が競合したらWeathermanを一時停止してください。"),
                ("de", "Nur du siehst das. Pausiere Weatherman, wenn beide den Himmel steuern."),
                ("fr", "Vous seul voyez ceci. Pausez Weatherman s’ils se disputent le ciel."),
                ("es", "Solo tú lo ves. Pausa Weatherman si ambos pelean por el cielo."),
                ("pt", "Só você vê isto. Pause o Weatherman se os dois brigarem pelo céu."),
                ("it", "Lo vedi solo tu. Metti in pausa Weatherman se i due litigare per il cielo."),
                ("zh-CN", "只有你看得到。若与 Weatherman 冲突请先暂停它。"),
                ("zh-TW", "只有你看得到。若與 Weatherman 衝突請先暫停它。"),
                ("ko", "나만 보입니다. 하늘이 겹치면 Weatherman을 일시 정지하세요."),
                ("ru", "Это видите только вы. Поставьте Weatherman на паузу, если оба правят небом.")),
        };
}
