<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <RootNamespace>Linkpearl.Platform.Ffxiv</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Linkpearl.Abstractions\Linkpearl.Abstractions.csproj" />
  </ItemGroup>

</Project>
