namespace Linkpearl.Platform;

public enum GameMenu : byte
{
    Character = 0,
    Inventory = 1,
    ArmouryChest = 2,
    Saddlebag = 3,
    Currency = 4,
    Achievements = 5,
    GoldSaucer = 6,
    MountGuide = 7,
    MinionGuide = 8,
    Companion = 9,
    PvpProfile = 10,
    BlueSpellbook = 11,
    Fashion = 12,
    Facewear = 13,
    AdventurerPlate = 14,
    Portraits = 15,
    Actions = 16,
    FriendList = 17,
    Blacklist = 18,
    Linkshell = 19,
    CrossWorldLinkshell = 20,
    FreeCompany = 21,
    Emotes = 22,
    PlayerSearch = 23,
    PartyFinder = 24,
    DutyFinder = 25,
    RaidFinder = 26,
    Journal = 27,
    ChallengeLog = 28,
    NoviceNetwork = 29,
}
